[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.26"
crossterm = "0.27"
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
uuid.workspace = true
chrono = { version = "0.4", features = ["serde"] }
core = { path = "../defs" }
storage = { path = "../storage" }
index = { path = "../index" }
api = { path = "../api" }
serde_json.workspace = true
reqwest = { version = "0.12", features = ["json", "blocking", "multipart"] }
dotenv = "0.15"